/*
 *  (c) Jason Wilden, 2026
 */

#include "drv.h"
#include "controller.h"

#define CONTROL_RATE  (46)             /* around 1000Hz */

static volatile uint16_t sample_count;
static volatile uint32_t aud_irq_count;
static struct midi_instance midi_in;
static struct controller controller;

static void process_block();
static void copy_data_to_VRAM();

int main(void)
{
  uint8_t led = 0;

  trace_init(TRACE);
  trace_print(TRACE, "Tracing API initialised.\n");

  controller_init(&controller);
  trace_print(TRACE, "Controller initialised.\n");

  while (1)
  {
    if (sample_count == 0)
    {
      /* Block pipeline from update during block processing */
      CLEAR_BIT(APCR->CR,APCR_CR_VRAM_UPDATE);
      process_block();
    }
    else if (sample_count == CONTROL_RATE)
    {
      copy_data_to_VRAM();      
      /* Signal audio pipeline that it can update */
      SET_BIT(APCR->CR,APCR_CR_VRAM_UPDATE);
      sample_count = 0; 
    }

    /* Heartbeat every second to show we're still alive and getting audio interrupts */
    if (aud_irq_count == 46875)
    {
      led = !led;
      led ? gpo_set_pin(GPO1, GPO_BSR_2) : gpo_clear_pin(GPO1, GPO_BSR_2);
      aud_irq_count = 0;
    }
  }

  /*NOTREACHED*/
  return 0;
}

/*
 * This calculates a block of voice data.  This is only modulation and voice
 * management functions.  Samples are generated by the audio pipeline.
 */
static void process_block()
{
  /* Process pending MIDI events from buffer */
  uint8_t byte;
  while (midi_buffer_read(&byte))
  {
    struct midi_msg *msg = midi_parse(&midi_in, byte);
    if (msg != NULL)
    {
      controller_handle_midi(&controller, msg);
    }
  }

  /* Update state and recalc modulators etc */
  controller_calculate(&controller);
}

/*
 * At BLOCK_SIZE samples we copy voice data into VRAM for the audio pipeline to
 * start using.  This ensures it happens between samples.  The audio pipeline
 * is operating at sample rate rather than block rate.
 */
static void copy_data_to_VRAM()
{
  // TODO: Copy voice data into VRAM and signal audio-pipeline
}

#define IRQ_AUDIO (1u << 3)
#define IRQ_MIDI (1u << 4)

void handle_irq(uint32_t mask)
{
  if (mask & IRQ_MIDI)
  {
    /*
     * Incoming MIDI byte, read from register and copy to midi buffer.
     */
    uint8_t byte = MIDI_STATUS_ACTIVE_SENSE; /* Temporary - MIDI NOP */

    midi_buffer_write(byte);
  }

  if (mask & IRQ_AUDIO)
  {
    /*
     * Just keep a count of the samples, these are used to indicate when a block
     * is calculated and when it is copied into VRAM (based on BLOCK_SIZE)
     */
    sample_count++;

    /* This is just for flashing LED during development  - heartbeat indicator */
    aud_irq_count++;
  }
}
