/*
 *  (c) Jason Wilden, 2026
 */

#include "drv.h"
#include "controller.h"

#define CONTROL_CYCLE_START_SAMPLE (1)
#define CONTROL_CYCLE_END_SAMPLE (46)

static volatile uint8_t current_sample;
static volatile uint32_t aud_irq_count;
static struct midi_instance midi_in;
static struct controller controller;

static void run_cycle();
static void copy_data_to_VRAM();

int main(void)
{
  uint8_t led = 0;

  trace_init(TRACE);
  trace_print(TRACE, "Tracing API initialised.\n");

  controller_init(&controller);
  trace_print(TRACE, "Controller initialised.\n");

  while (1)
  {
    /*
     * This is the control rate process/update cycle. Timing is based on counting samples, the
     * control rate signals update slower than the sample rate (approx 1kHz).  
     */
    if (current_sample == CONTROL_CYCLE_START_SAMPLE)
    {
      /*
       * At the start of the cycle we set the control register so that the audio pipeline cannot
       * update from VRAM while we're updating it.  We then run the cycle to advance all the modulators
       * and voice lifecycles.  Finally we copy the data into VRAM.
       * 
       * This needs to complete before we reach the CONTROL_CYCLE_END_SAMPLE otherwise the update
       * will be missed.  
       */
      CLEAR_BIT(APCR->CR, APCR_CR_VRAM_UPDATE);
      run_cycle();
      copy_data_to_VRAM();
    }

    if (current_sample == CONTROL_CYCLE_END_SAMPLE)
    {
      /*
       * At the end of the control-rate cycle we indicate to the pipeline to
       * update state VRAM. It will do this before generating the next sample ensuring we
       * update between samples to avoid gltches.
       */
      SET_BIT(APCR->CR, APCR_CR_VRAM_UPDATE);
      current_sample = 0;
    }

    /* Heartbeat every second to show we're still alive and getting audio interrupts */
    if (aud_irq_count == 46875)
    {
      led = !led;
      led ? gpo_set_pin(GPO1, GPO_BSR_2) : gpo_clear_pin(GPO1, GPO_BSR_2);
      aud_irq_count = 0;
    }
  }

  /*NOTREACHED*/
  return 0;
}

/*
 * This calculates a block of voice data.  This is only modulation and voice
 * management functions.  Samples are generated by the audio pipeline.
 */
static void run_cycle()
{
  /* Process pending MIDI events from buffer */
  uint8_t byte;
  while (midi_buffer_read(&byte))
  {
    struct midi_msg *msg = midi_parse(&midi_in, byte);
    if (msg != NULL)
    {
      controller_handle_midi(&controller, msg);
    }
  }

  /* Update state and recalc modulators etc */
  controller_calculate(&controller);
}

/*
 * At BLOCK_SIZE samples we copy voice data into VRAM for the audio pipeline to
 * start using.  This ensures it happens between samples.  The audio pipeline
 * is operating at sample rate rather than block rate.
 */
static void copy_data_to_VRAM()
{
  // TODO: Copy voice data into VRAM and signal audio-pipeline
}

#define IRQ_AUDIO (1u << 3)
#define IRQ_MIDI (1u << 4)

void handle_irq(uint32_t mask)
{
  uint32_t current_sample;

  if (mask & IRQ_MIDI)
  {
    /*
     * Incoming MIDI byte, read from register and copy to midi buffer.
     */
    uint8_t byte = MIDI_STATUS_ACTIVE_SENSE; /* Temporary - MIDI NOP */

    midi_buffer_write(byte);
  }

  if (mask & IRQ_AUDIO)
  {
    current_sample++;

    /* This is just for flashing LED during development  - heartbeat indicator */
    aud_irq_count++;
  }
}
