/*
 *  (c) Jason Wilden, 2026
 */

#include "drv.h"

#include "synth.h"

static volatile uint8_t aud_sample;
static volatile uint8_t aud_irq_count;
static struct midi_instance midi_in;
static struct synth synth;

static void CalculateVoiceData();
static void VoiceDataToVRAM();

int main(void)
{
  uint8_t led = 0;

  trace_init(TRACE);
  trace_print(TRACE, "Tracing API initialised.\n");

  synth_init(&synth);
  trace_print(TRACE, "Synth initialised.\n");

  while (1)
  {
    if (aud_sample == 0)
    {
      CalculateVoiceData();
    }
    else if (aud_sample == BLOCK_SIZE)
    {
      VoiceDataToVRAM();
      aud_sample = 0;
    }

    /* Heartbeat to show we're still alive and getting audio interrupts */
    if (aud_irq_count == 46880)
    {
      led = !led;
      led ? gpo_set_pin(GPO1, GPO_BSR_2) : gpo_clear_pin(GPO1, GPO_BSR_2);
      aud_irq_count = 0;
    }
  }

  /*NOTREACHED*/
  return 0;
}

/*
 * This calculates a block of voice data.  This is only modulation and voice
 * management functions.  Samples are generated by the audio pipeline.
 */
static void CalculateVoiceData()
{
  /* Process pending MIDI events from buffer */
  uint8_t byte;
  while (midi_buffer_read(&byte))
  {
    struct midi_msg *msg = midi_parse(&midi_in, byte);
    if (msg != NULL)
    {
      synth_handle_midi(&synth, msg);
    }
  }

  /* Update state and recalc modulators etc */
  synth_calculate(&synth);
}

/*
 * At BLOCK_SIZE samples we copy voice data into VRAM for the audio pipeline to
 * start using.  This ensures it happens between samples.  The audio pipeline
 * is operating at sample rate rather than block rate.
 */
static void VoiceDataToVRAM()
{
  // TODO: Copy voice data into VRAM and signal audio-pipeline
}

#define IRQ_AUDIO (1u << 3)
#define IRQ_MIDI (1u << 4)

void handle_irq(uint32_t mask)
{
  if (mask & IRQ_MIDI)
  {
    /*
     * Incoming MIDI byte, read from register and copy to midi buffer.
     */
    uint8_t byte = MIDI_STATUS_ACTIVE_SENSE; /* Temporary - MIDI NOP */

    midi_buffer_write(byte);
  }

  if (mask & IRQ_AUDIO)
  {
    /*
     * Just keep a count of the samples, these are used to indicate when a block
     * is calculated and when it is copied into VRAM (based on BLOCK_SIZE)
     */
    aud_sample++;
    aud_irq_count++;
  }
}
