#!/usr/bin/env python3
# ------------------------------------------------------------------------------
# (c) Jason Wilden, 2026
# ------------------------------------------------------------------------------
# This script generates tables used by the envelope generator in Q1.15 fixed
# decimal format.
#
# The picorv32 has no FPU an no math functions.  These LUT avoids porting exp
# and log functions to fixed point.  
# ------------------------------------------------------------------------------
import math

SAMPLE_RATE = 46875.0       # Actual Fs (including any error)
BLOCK_SIZE = 32             # Cycle length
ENV_TIME_MIN_MS = 1.0       # Fastest time (ms)
ENV_TIME_MAX_MS = 8000.0    # Slowest time (ms)
NUM_STEPS = 128             # MIDI maximum
Q15_ONE = 32767             #  Max positive

ATTACK_TCO = math.exp(-1.5) #  Attack Time Constant Overshoots
DECAY_RELEASE_TCO = math.exp(-4.95) 

# Maps the 7-bit MIDI value onto the time range - this is used for velocity
# scaling.  Velocity modifies the envelope lengths rather than just changing
# volume.
def midi_to_ms(midi_val: int) -> float:
    t = midi_val / (NUM_STEPS - 1)
    return ENV_TIME_MIN_MS + t * (ENV_TIME_MAX_MS - ENV_TIME_MIN_MS)

# Converts a duration in ms to a duration in blocks (fractional)
def ms_to_blocks(ms: float) -> float:    
    blocks = (ms / 1000.0) * SAMPLE_RATE / BLOCK_SIZE
    return max(blocks, 1.0)  # ensure at least 1 block.

# Per block multiplier for segment
def redmon_coeff(tco: float, blocks: float) -> float:    
    return math.exp(-math.log((1.0 + tco) / tco) / blocks)

# Quantise a normalised float to Q1.15 format.
def to_q15(x: float) -> int:
    val = round(x * 32768.0)
    return max(0, min(val, Q15_ONE))

# Here onwards is the generation of the output tables
def generate_coeff_table(tco: float) -> list[int]:
    table = []
    for midi_val in range(NUM_STEPS):
        ms = midi_to_ms(midi_val)
        blocks = ms_to_blocks(ms)
        coeff = redmon_coeff(tco, blocks)
        table.append(to_q15(coeff))
    return table

def format_c_array(name: str, values: list[int], per_line: int = 8) -> str:
    lines = [f"const Q1_15 {name}[{len(values)}] = {{"]
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        row = ", ".join(f"0x{v:04X}" for v in chunk)
        lines.append(f"    {row},")
    lines.append("};")
    return "\n".join(lines)


def main():
    attack_table  = generate_coeff_table(ATTACK_TCO)
    decay_table   = generate_coeff_table(DECAY_RELEASE_TCO)   # release reuses this table (same tco)

    print("/*")
    print(" * Generated by env_gen_luts.py ")
    print(f" * DAE_SAMPLE_RATE={SAMPLE_RATE}, DAE_AUDIO_BLOCK_SIZE={BLOCK_SIZE}")
    print(f" * ENV_TIME_MIN_MS={ENV_TIME_MIN_MS}, ENV_TIME_MAX_MS={ENV_TIME_MAX_MS}")
    print(" */")
    print()
    print(format_c_array("env_attack_coeff_lut", attack_table))
    print()
    print(format_c_array("env_decay_release_coeff_lut", decay_table))
    print()

    # print("/*")
    # print(f" *   MIDI 0   -> {midi_to_ms(0):8.2f} ms  attack_coeff=0x{attack_table[0]:04X}")
    # print(f" *   MIDI 64  -> {midi_to_ms(64):8.2f} ms  attack_coeff=0x{attack_table[64]:04X}")
    # print(f" *   MIDI 127 -> {midi_to_ms(127):8.2f} ms  attack_coeff=0x{attack_table[127]:04X}")
    # print(" */")


if __name__ == "__main__":
    main()